### ISSUE TITLE
s3tranfer / botocore dependencies need update

### ISSUE THREAD

**Issue by timbaer** [artsy/jenkins-backup-s3#11]
We are seeing the following error when executing the script in the current version. When we explicitly reinstall s3transfer and botocore to match the desired versions, described in the setup.py file, the script is running fine again. 

```
+ backup-jenkins ...
Traceback (most recent call last):
  File "/usr/bin/backup-jenkins", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 's3transfer==0.1.11' distribution was not found and is required by jenkins-backup-s3
```

Performing a ```pip show s3transfer``` shows that version 0.1.13 is installed locally. ```pip show botocore``` shows 1.10.0 to be installed on my system.

I digged into the boto 1.4.7 dependencies (https://github.com/boto/boto3/releases/tag/1.4.7) and found the following line in their setup file:

```
requires = [
    'botocore>=1.7.0,<1.8.0',
    'jmespath>=0.7.1,<1.0.0',
    's3transfer>=0.1.10,<0.2.0'
]
```

I'm not familiar with the python setup-flow, but from my point of view, these requirement definitions do collide with the ones stated in this project. Overall, why do you explicitly define the s3transfer and botocore dependencies at all? Aren't they transitively added?

**Comment by timbaer** [comment]
Hi guys,

can you provide any information on this issue? Am I doing it all wrong? Can you point me to a valid solution so that I can suggest a PR?

**Comment by izakp** [comment]
Thanks for the report @timbaer - sorry I was not getting notifications to my personal email address for this repo.

A standard way to isolate a project's library dependency versions is to use virtualenvs - see https://docs.python-guide.org/dev/virtualenvs/

In any case I'll check to see that these dependencies can be safely upgraded.

**Comment by izakp** [comment]
Closed via https://github.com/artsy/jenkins-backup-s3/pull/15
