### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by mikejw** [artsy/jenkins-backup-s3#16]
Hi there,
I'm just wondering if this has been tested for situations where there are job(s) running while a backup is being attempted to be created or restored.  I've spent a bit of time researching remotely disabling jobs via the Jenkins restul api but have found that this seems impossible to do for multibranch pipeline jobs.

Cheers,
Mike

**Comment by izakp** [comment]
Hi @mikejw - sorry for the delay, I'm having problems getting notifications for new issues.  I have not tested this situation you describe extensively as we are not relying on this as a specific point-in-time recovery, only doing a nightly backup when no other jobs are scheduled.

Providing a satisfactory answer would require looking into how Jenkins syncs its build XML definitions to disk, as these scripts are simply archiving the build directories.

I'd advise scheduling this job when other builds are not running and/or using Jenkins' quietDown mode if you're concerned with missing or duplicating a job when restoring from a backup.
