### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rclmenezes** [artsy/jenkins-backup-s3#2]
This is a great little script. Would be nice if we had a license.

Also, adding a `setup.py` and making it available on PyPI/pip would be nice!

**Comment by dblock** [comment]
Yep, @orta. All our OSS is MIT licensed so we'll add that.

**Comment by izakp** [comment]
Closed via https://github.com/artsy/jenkins-backup-s3/commit/e53ed2c2295e7d9b73747efecea289b385675dee
