### ISSUE TITLE
Prune undesirably removes too many backup files

### ISSUE THREAD

**Issue by timbaer** [artsy/jenkins-backup-s3#8]
When pruning backup files, I expect to keep the last "n" backups in my backup-bucket, when "n" is provided as prune-argument like

`backup jenkins --backup some --backup-region eu-west-1 prune n. `

However, we experienced for n=1 that ALL backed up files got removed from s3. After some digging into the code, we figured out that the problem is with this line: 

https://github.com/artsy/jenkins-backup-s3/blob/e150656d2343429b97f137d39c5ba4bff8fe984d/jenkins_backup_s3/backup.py#L208

I played around with python and figured out, that the using "keep" like done here, means it is used as the stepsize. 

```
>>> L=range(10)
>>> L
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> L[::1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> L[::2]
[0, 2, 4, 6, 8]
```
So, it makes absolutely sense that all my backups got removed when calling "prune 1". 

Now, is it the desired behaviour? Like I said, I would expect sth. like 

`for backup_id in s3.backups()[keep + 1::]:`

```
>>> keep=1
>>> L[keep+1::]
[2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by izakp** [comment]
Thanks for uncovering this @timbaer - and sorry you lost backups :/  The desired behavior is to get a slice of the array from index `keep` to the end - so `L[keep:]` (0-based index and all)

Should also probably be sorted by timestamps, and not assume that the S3 list bucket operation returns objects sorted.

Will PR

**Comment by izakp** [comment]
Fixed in https://github.com/artsy/jenkins-backup-s3/pull/10
